name: kadai4
on: [push]
jobs:
  io_test:
    name: Use Linux commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission Setting
        run: chmod +x gcm.sh random_test_gcm.sh
      - name: Test Run
        run: ./random_test_gcm.sh

